# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  agendamentoapi:
    image: agendamentoapi
    build:
      context: .
      dockerfile: AgendamentoAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5217:5217
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
